#ifndef _CLOG_DEFS_H_
#define _CLOG_DEFS_H_

enum CLogLevels {
  CLL_NONE    = 0,
  CLL_FATAL   = 1,
  CLL_ERROR   = 2,
  CLL_WARN    = 3,
  CLL_INFO    = 4,
  CLL_DEBUG   = 5,
  CLL_TRACE   = 6,
  CLL_VERBOSE = 7,
  CLL_COUNT
};

#define CLOG_FATAL(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_FATAL,HIDDENMSG, __VA_ARGS__)
#define CLOG_ERR(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_ERROR,HIDDENMSG, __VA_ARGS__)
#define CLOG_WARN(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_WARN,HIDDENMSG, __VA_ARGS__)
#define CLOG_INFO(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_INFO,HIDDENMSG, __VA_ARGS__)
#define CLOG_DBG(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_DEBUG,HIDDENMSG, __VA_ARGS__)
#define CLOG_TRACE(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_TRACE,HIDDENMSG, __VA_ARGS__)
#define CLOG_VERBOSE(PTR_OR_MODULEID,HIDDENMSG,...) CLOG_LOG(PTR_OR_MODULEID,CLL_VERBOSE,HIDDENMSG, __VA_ARGS__)
#define CLOG_DEBUG CLOG_DBG
#define CLOG_ERROR CLOG_ERR

#endif // _CLOG_DEFS_H_
